// src/store/modules/estabelecimento/auth/types.js

const types = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  FETCH_AGENDAMENTOS_REQUEST: "FETCH_AGENDAMENTOS_REQUEST",
  FETCH_AGENDAMENTOS_SUCCESS: "FETCH_AGENDAMENTOS_SUCCESS",
  FETCH_AGENDAMENTOS_FAILURE: "FETCH_AGENDAMENTOS_FAILURE",
  // outros tipos...
};

export default types;
